Order model incorporation.
ponomvrenko/online-book-store pull request #11
Opened 2024-01-04 22:48 UTC by ponomvrenko

The endpoints created by this branch have enabled it to manage orders, allowing users to create them, receive information, and update them (for admin).

2024-01-05 12:53 UTC, AgroFix approved these changes
![зображення_2024-01-05_145044927](https://github.com/ponomvrenko/online-book-store/assets/89842485/95c9fa57-3c8a-4c6e-9772-d2b80f8579fd)
Change branch "master" to "shoppingcart". Cause i see all of your commits!

2024-01-05 12:53 UTC, AgroFix commented on src/main/java/com/example/onlinebookstore/dto/order/OrderResponseDto.java
> +    private Set<OrderItemResponseDto> orderItems;
```suggestion
    @EqualsAndHashCode.Exclude
    @ToString.Exclude
    private Set<OrderItemResponseDto> orderItems;
```

2024-01-05 12:53 UTC, AgroFix commented on src/main/java/com/example/onlinebookstore/model/Order.java
> +@Where(clause = "is_deleted=false")
```suggestion
@SQLRestriction("is_deleted=false")
```
@Where is is deprecated

2024-01-05 12:53 UTC, AgroFix commented on src/main/java/com/example/onlinebookstore/model/OrderItem.java
> +@Where(clause = "is_deleted=false")
```suggestion
@SQLRestriction("is_deleted=false")
```
@Where is is deprecated

2024-01-05 12:53 UTC, AgroFix commented on src/main/resources/db/changelog/changes/11-create-shopping-carts-table.yaml
> +                    nullable: false
when column is primary key constraint nullable is redundant, because primary key is unique + not null.

2024-01-05 12:53 UTC, AgroFix commented on src/main/resources/db/changelog/changes/12-create-cart-items-table.yaml
> +                    nullable: false
when column is primary key constraint nullable is redundant, because primary key is unique + not null.

2024-01-05 12:53 UTC, AgroFix commented on src/main/resources/db/changelog/changes/14-create-order-items-table.yaml
> +                    nullable: false
when column is primary key constraint nullable is redundant, because primary key is unique + not null.

2024-01-05 13:48 UTC, vovasalyha requested changes
Please change the base branch for this PR or merge all previous pull requests. Because there are changes from other homeworks.

2024-01-05 15:58 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2024-01-05 15:58 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/dto/order/OrderUpdateRequestDto.java
> +    @NotBlank
```suggestion
    @NotNull
```

2024-01-05 15:58 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/dto/order/OrderUpdateRequestDto.java
> +    private String status;
```suggestion
    private Order.Status status;
```

2024-01-05 15:58 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/model/Order.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-01-05 15:58 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/model/OrderItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-01-05 15:58 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/model/OrderItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-01-05 15:58 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +    public OrderResponseDto placeOrder(Long userId, OrderPlaceRequestDto requestDto) {
Can you simplify this method? (by extracting some logical parts into separate private methods for example)

2024-01-05 15:58 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-01-08 09:49 UTC, yevheniisynytsia requested changes

2024-01-08 09:49 UTC, yevheniisynytsia commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +        order.setStatus(Order.Status.valueOf(Order.Status.PENDING.name()));
```suggestion
        order.setStatus(Order.Status.PENDING);
```

2024-01-08 10:21 UTC, d1sam approved these changes
well done!

2024-01-08 10:46 UTC, merged