Adding docker
ponomvrenko/online-book-store pull request #12
Opened 2024-01-08 11:39 UTC by ponomvrenko

2024-01-08 14:53 UTC, MinoDentori approved these changes
GJ!

2024-01-08 15:52 UTC, vovasalyha requested changes
Did you run your solutions? Because when I tried, it cannot run and fails because of configuration problems.

2024-01-08 15:52 UTC, vovasalyha commented on .env
> +MYSQL_USER=root
MYSQL_USER is reserved variable name in MySQL, so whether specify other name, or specify other user, because root is created by default.

2024-01-08 15:52 UTC, vovasalyha commented on docker-compose.yml
> +      - MYSQL_USER:$MYSQL_USER
Are you sure you are passing params correctly?

2024-01-08 18:04 UTC, ponomvrenko commented
I've pushed previous code after simple docker build command, now I rewrote docker-compose.yml & .env for avoiding some SQLConnectionException that occurs while docker image starts. 
I'm providing screenshots that my docker container runs and works properly:
![image](https://github.com/ponomvrenko/online-book-store/assets/63046976/d8626fae-223e-45ee-a388-558c2b39f25d)
![image](https://github.com/ponomvrenko/online-book-store/assets/63046976/ea92b0b6-385d-4cd6-8b27-2ed6cc8c0d38)

2024-01-09 06:58 UTC, yevheniisynytsia approved these changes
confirming that `docker-compose up` works as expected. Well done!

2024-01-09 06:58 UTC, yevheniisynytsia commented on pom.xml
> +        <testcontainers.version>1.18.0</testcontainers.version>
out of the scope of this PR

2024-01-09 06:58 UTC, yevheniisynytsia commented on pom.xml
> +        </dependency>
out of the scope of this PR

2024-01-09 06:58 UTC, yevheniisynytsia commented on pom.xml
> +
same

2024-01-09 07:18 UTC, yevheniisynytsia approved these changes

2024-01-09 09:59 UTC, merged