Adding tests for book and category
ponomvrenko/online-book-store pull request #13
Opened 2024-01-10 08:31 UTC by ponomvrenko

2024-01-10 10:01 UTC, BohdanTrue approved these changes
GJ

2024-01-10 10:01 UTC, BohdanTrue commented on src/test/java/com/example/onlinebookstore/controller/CategoryControllerTest.java
> +        }
Do you haven't problems here?
You add your books, categories and books_categories in that order
1. books
2. categories
3. books_categories

But you delete in that order
1. books (in my case book_categories, because this table already have dependencies from categories and books_categories tables)
2. categories (in my case, same)
3. books_categories (in my case books)

Think about it, how correct do you delete objects from your tables.

2024-01-10 10:01 UTC, BohdanTrue commented on src/test/java/com/example/onlinebookstore/service/impl/BookServiceImplTest.java
> +        assertEquals(expected.getIsbn(), actual.getIsbn());
Not necessary, but you can use `EqualsBuilder.reflectionEquals(expected, actual)`

2024-01-10 10:01 UTC, BohdanTrue commented on src/test/resources/database/books/delete-default-book.sql
Add one empty line in all of your sql scripts

2024-01-10 12:36 UTC, ponomvrenko commented on src/test/java/com/example/onlinebookstore/controller/CategoryControllerTest.java
> +        }
Thanks for idea. I'm also thought in this way, so I changed order logically.

2024-01-11 11:14 UTC, yevheniisynytsia requested changes
Awesome work! A lot of quality tests with some small mistakes! Well done!

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/controller/BookControllerTest.java
> +    private CreateBookRequestDto getDefaultCreateBookRequestDto() {
👍

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/controller/CategoryControllerTest.java
> +        CategoryResponseDto[] actual = objectMapper.readValue(
you can readValue into list and not map array to list then

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/impl/BookServiceImplTest.java
> +    private BookServiceImpl bookService;
place it after mocks

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/impl/BookServiceImplTest.java
> +            save() works properly and returns dto
```suggestion
            Save book, returns valid DTO
```

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/impl/BookServiceImplTest.java
> +        assertEquals(expected, actual);
it is better to compare whole object instead of its part

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/impl/BookServiceImplTest.java
> +            findById() should return Exception with invalid ID
```suggestion
            Find bood by id, should return Exception with invalid ID
```
make more human-readable names

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/impl/BookServiceImplTest.java
> +        assertEquals(expected.getPrice(), actual.getPrice());
this line is redundant as it is a part of previous line

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/impl/BookServiceImplTest.java
> +            updateById() should throw Exception with incorrect ID
please make name more readable

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/impl/CategoryServiceImplTest.java
> +            save() works properly and returns dto
same

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/impl/CategoryServiceImplTest.java
> +        assertEquals(expected.getName(), actual.getName());
redundant

2024-01-11 11:14 UTC, yevheniisynytsia commented on src/test/resources/database/books-categories/delete-books-categories.sql
> +DELETE FROM books_categories;
add empty lines

2024-01-15 07:08 UTC, yevheniisynytsia approved these changes

2024-01-15 07:08 UTC, yevheniisynytsia commented on src/test/java/com/example/onlinebookstore/service/impl/BookServiceImplTest.java
> +    @DisplayName("Find book by ID, should return exception with")
not finished name

2024-01-15 15:05 UTC, merged