Adding first version of readme.md
ponomvrenko/online-book-store pull request #14
Opened 2024-01-10 15:56 UTC by ponomvrenko

2024-01-11 09:13 UTC, d1sam requested changes
Good job, but there are some improvements should be done!

2024-01-11 09:13 UTC, d1sam commented on readme.md
> +
what about testing technologies? please also write categories, that related to technologies.

2024-01-11 09:13 UTC, d1sam commented on readme.md
Where is example of your endpoints?

2024-01-11 09:13 UTC, d1sam commented on readme.md
> +**Solution:** We developed a global handler and custom exceptions for better error reporting.
please describe detailer problems and solutions.

2024-01-11 09:13 UTC, d1sam commented on readme.md
please also add Possible improvements section.

2024-01-15 08:14 UTC, yevheniisynytsia requested changes
Well done! Small changes left

2024-01-15 08:14 UTC, yevheniisynytsia commented on readme.md
> +**Spring Boot Starter Test:** Provides testing support for Spring Boot applications.
+ Mockito

2024-01-15 08:14 UTC, yevheniisynytsia commented on readme.md
> ++ `GET: /api/categories/{id}` - The endpoint for searching a specific category (User authority)
for consistency let's write with User authority

2024-01-15 08:14 UTC, yevheniisynytsia commented on readme.md
> +2. Build project and download dependencies for Maven with command: `mvn clean install`
make sure you have docker up and running

2024-01-15 09:45 UTC, ponomvrenko commented on readme.md
> +2. Build project and download dependencies for Maven with command: `mvn clean install`
![Uploading image.png…]()

2024-01-15 10:16 UTC, d1sam approved these changes
well done!

2024-01-15 14:18 UTC, merged