Spring boot security incorporation
ponomvrenko/online-book-store pull request #7
Opened 2023-12-26 06:59 UTC by ponomvrenko

2023-12-26 14:03 UTC, BolsunovaNataliia approved these changes

2023-12-26 14:03 UTC, BolsunovaNataliia commented on pom.xml
>              <groupId>org.springframework.boot</groupId>
Good job! But I have a few clarifications.

2023-12-26 14:03 UTC, BolsunovaNataliia commented on src/main/resources/db/changelog/changes/06-create-users-roles-table.yaml
> +databaseChangeLog:
It's not correct. This table have to consist of 2 columns: user_id, role_id as one privary key

2023-12-26 14:03 UTC, BolsunovaNataliia commented on src/main/resources/db/changelog/changes/07-insert-data-to-users-roles-table.yaml
> +databaseChangeLog:
You have to supply query instead hard code ("1" or "2") for user_id and role_id

2023-12-26 14:03 UTC, BolsunovaNataliia commented on src/main/resources/db/changelog/changes/07-insert-data-to-users-roles-table.yaml
> +  - changeSet:
Where is your change set to insert users to users table?

2023-12-26 14:27 UTC, andrii-hoienko requested changes

2023-12-26 14:27 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/model/User.java
> +    private Set<Role> roles = new HashSet<>();
Please exclude this from equals/hashCode and toString

2023-12-26 14:27 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/06-create-users-roles-table.yaml
> +databaseChangeLog:
Agree there is no need for separate column for Id, PK of this table could be composed with 2 fields

2023-12-27 08:17 UTC, d1sam requested changes
Good job, but some changes should be done!

2023-12-27 08:17 UTC, d1sam commented on src/main/resources/db/changelog/changes/08-insert-roles-to-users-roles-table.yaml
try to improve your code and use valueComputed with preConditions for your insert.
Example:
```
      preConditions:
        - sqlCheck:
            expectedResult: 1
            sql: SELECT COUNT(*) FROM users WHERE email='admin@example.com'
        - sqlCheck:
            expectedResult: 1
            sql: SELECT COUNT(*) FROM roles WHERE name='ROLE_ADMIN'
      changes:
        - insert:
            tableName: user_role
            columns:
              - column:
                  name: user_id
                  valueComputed: (SELECT id FROM users WHERE email='admin@example.com')
              - column:
                  name: role_id
                  valueComputed: (SELECT id FROM roles WHERE name='ROLE_ADMIN')
```

2023-12-27 08:17 UTC, d1sam commented on src/main/java/com/example/onlinebookstore/repository/RoleRepository.java
> +public interface RoleRepository extends JpaRepository<Role, Long> {
```suggestion
@Repository
public interface RoleRepository extends JpaRepository<Role, Long> {
```

2023-12-27 16:01 UTC, vovasalyha approved these changes
GJ

2023-12-27 19:54 UTC, merged