Category implementation
ponomvrenko/online-book-store pull request #9
Opened 2023-12-28 13:12 UTC by ponomvrenko

2023-12-28 14:56 UTC, DevIgork approved these changes
lgtm

2023-12-28 15:33 UTC, d1sam requested changes
looks good, but some changes should be done :)

2023-12-28 15:33 UTC, d1sam commented on src/main/java/com/example/onlinebookstore/model/Category.java
> +    private String description;
```suggestion
    @Column
    private String description;
```

2023-12-28 15:33 UTC, d1sam commented on src/main/java/com/example/onlinebookstore/model/Category.java
> +@Data
```suggestion
@Data
@NoArgsConstructor
```

2023-12-28 15:33 UTC, d1sam commented on src/main/java/com/example/onlinebookstore/service/impl/CategoryServiceImpl.java
> +        if (existingCategory.isEmpty()) {
let's better use `.orElseThrow`

2023-12-28 15:33 UTC, d1sam commented on src/main/resources/db/changelog/changes/09-create-categories-table.yaml
> +                    nullable: false
```suggestion
```
you have primary key, that's why nullable constraint is unnecessary

2023-12-29 07:15 UTC, d1sam approved these changes
well done!

2023-12-30 09:53 UTC, merged